theme: jekyll-theme-minimal
title: Hardware Info & Monitor Utility for ChromeOS
description: Simple & Powerful Hardware Information Utility for ChromeOS allowing users to monitor their hardware info & usage without leaving their browser.
